advcbv/adv_cbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path("basic_app/", include("basic_app.urls", namespace="basic_app"))
]

advcbv/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = "basic_app"

urlpatterns = [
    path("", views.SchoolListView.as_view(), name="school_list"),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='school_detail'),
    path("create/", views.SchoolCreateView.as_view(), name="school_create"),
    path("update/<int:pk>", views.SchoolUpdateView.as_view(), name="school_update"),
    path("delete/<int:pk>", views.SchoolDeleteView.as_view(), name="school_delete"),
]

advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.


class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:school_detail", kwargs={"pk": self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(
        School, related_name="students", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

advcbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from basic_app import models
from django.urls import reverse_lazy

# Create your views here.


class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        ''' Adds a context to the template '''
        context = super().get_context_data(**kwargs)
        context["injected"] = "Basic injection"
        return context


class SchoolListView(ListView):
    context_object_name = "school_list"
    model = models.School
    template_name = "basic_app/school_list.html"


class SchoolDetailView(DetailView):
    context_object_name = "school_detail"
    model = models.School
    template_name = "basic_app/school_detail.html"


class SchoolCreateView(CreateView):
    # template_name = "basic_app/school_create.html"
    model = models.School
    fields = ("name", "principal", "location")


class SchoolUpdateView(UpdateView):
    # template_name = "basic_app/school_update.html"
    model = models.School
    fields = ("name", "principal", "location")


class SchoolDeleteView(DeleteView):
    # template_name = "basic_app/school_delete.html"
    # context_object_name = school
    model = models.School
    success_url = reverse_lazy("basic_app:school_list")


class CBView(View):
    def get(self, request):
        return HttpResponse("This is a class based view")

advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>
    {% block title %}

    {% endblock title %}
    </title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'basic_app:school_list' %}">Schools</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

  <!-- Latest compiled and minified jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>

advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}

{% block title %}
  School Confirm Delete
{% endblock title %}

{% block body_block %}
<div class="jumbotron">
    <h1> Delete {{ school.name }}? </h1>
    <form class="form-check"> 
        {% csrf_token %}
        <input type="button" value="Delete" class="btn btn-danger">
        <a href="{% url "basic_app:school_detail" pk=school.pk %}" class="btn btn-primary"> Cancel <a> 
    </form>
</div>
{% endblock body_block %}

advcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %} 

{% block title %}
  School Details
{% endblock title %}

{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to the School Detail Page</h1>
  <h2>School Details:</h2>
  <p>Id_num: {{school_detail.id}}</p>
  <p>Name: {{school_detail.name}}</p>
  <p>Principal: {{school_detail.principal}}</p>
  <p>Location: {{school_detail.location}}</p>

  <h3>Students:</h3>
  {% for student in school_detail.students.all %}
  <p>{{student.name}} who is {{student.age}} years old.</p>
  {% endfor %}
</div>

<div class="container">
  <p>
    <a href="{% url "basic_app:school_update" pk=school_detail.pk %}" class="btn btn-primary"> Update information </a> 
    <a href="{% url "basic_app:school_delete" pk=school_detail.pk %}" class="btn btn-danger"> Delete information </a> 
  </p> 
</div>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block title %}
  School Form 
{% endblock title %}

{% block body_block %}
<div class="jumbotron">
   <h1> Welcome to school form </h1>
   <h1> 
        {% if not form.instance.pk %}
        Create School
        {% else %}
        Update School
        {% endif %}
   </h1> 
   <form method="POST" class="form-check">
       {% csrf_token %}
       {{ form.as_p }}
       <input type="submit" value="Submit">
   </form>
</div>
{% endblock body_block %}

advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %} 

{% block title %}
  School List
{% endblock title %}

{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to the List of Schools Page!</h1>
  <ol>
    {% for school in school_list %}
    <h2>
      <li><a href="{{school.id}}/">{{school.name}} </a></li>
    </h2>
    {% endfor %}
  </ol>
</div>

{% endblock %}

advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <title>
      {% block title %} {% endblock title %}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <ul class="nav navbar-nav">
        <li class="nav-item navbar-brand"> <a href="{% url "basic_app:school_list" %}"> Schools </a> </li>
        <li class="nav-item navbar-brand"> <a href="{% url "admin:index" %}"> Admin </a> </li>
      </ul>
    </nav>
    <div class="container">
      {% block body_block %} {% endblock body_block %}
    </div>
  </body>
</html>

advcbv/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block title %}
    Home
{% endblock title%}

{% block body_block %}
    <div class="jumbotron">
        <h1>Home Page!</h1> 
    </div> >
{% endblock body_block %}